on:
  push:
    tags:
      - "dryrun/[0-9]+.[0-9]+.[0-9]+"
      - "release/[0-9]+.[0-9]+.[0-9]+"

name: Deploy Extension

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DryRun
        id: releaseMode
        # perform secret check & put boolean result as an output
        shell: bash
        env:
          GIT_REF: ${{ github.ref }}
        run: |
          if [[ "$GIT_REF" = "refs/tags/dryrun"* ]]; then
            echo "dryRun=true" >> $GITHUB_OUTPUT;
          else
            echo "dryRun=false" >> $GITHUB_OUTPUT;
          fi
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - run: npm ci
      - name: Publish to Open VSX Registry
        if: success() || failure()
        uses: HaaLeo/publish-vscode-extension@f4ece70f329f66686bd71c54b1671353fe320e49 # v1
        id: publishToOpenVSX
        with:
          dryRun: ${{ steps.releaseMode.outputs.dryRun }}
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          preRelease: false
          skipDuplicate: true
      - name: Publish to Visual Studio Marketplace
        if: success() || failure()
        uses: HaaLeo/publish-vscode-extension@f4ece70f329f66686bd71c54b1671353fe320e49 # v1
        with:
          dryRun: ${{ steps.releaseMode.outputs.dryRun }}
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          preRelease: false
          registryUrl: https://marketplace.visualstudio.com
          skipDuplicate: true
      - name: Github Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        if: ${{ ! steps.releaseMode.outputs.dryRun }}
        with:
          body: |
            This release is also available on the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=SocketSecurity.vscode-socket-security) and [OpenVSX Registry](https://open-vsx.org/extension/SocketSecurity/vscode-socket-security).
          files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          prerelease: ${{ steps.releaseMode.outputs.preRelease }}
