on:
  push:
    tags:
      - "dryrun/[0-9]+.[0-9]+.[0-9]+"
      - "release/[0-9]+.[0-9]+.[0-9]+"

name: Deploy Extension

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check for DryRun
        id: releaseMode
        # perform secret check & put boolean result as an output
        shell: bash
        env:
          GIT_REF: ${{ github.ref }}
        run: |
          if [[ "$GIT_REF" = "refs/tags/dryrun"* ]]; then
            echo "dryRun=true" >> $GITHUB_OUTPUT;
          else
            echo "dryRun=false" >> $GITHUB_OUTPUT;
          fi
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      - run: npm ci
      - name: Publish to Open VSX Registry
        if: success() || failure()
        uses: SocketDev/socket-registry/.github/actions/publish-vscode-extension@4e9a0575c474ea9bc5587d3554608a155307111c # main (2026-05-15)
        id: publishToOpenVSX
        with:
          dry-run: ${{ steps.releaseMode.outputs.dryRun }}
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          pre-release: false
          registry-url: https://open-vsx.org/api
          skip-duplicate: true
      - name: Publish to Visual Studio Marketplace
        if: success() || failure()
        uses: SocketDev/socket-registry/.github/actions/publish-vscode-extension@4e9a0575c474ea9bc5587d3554608a155307111c # main (2026-05-15)
        with:
          dry-run: ${{ steps.releaseMode.outputs.dryRun }}
          extension-file: ${{ steps.publishToOpenVSX.outputs.vsix-path }}
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          pre-release: false
          registry-url: https://marketplace.visualstudio.com
          skip-duplicate: true
      - name: Github Release
        uses: SocketDev/socket-registry/.github/actions/create-gh-release@4e9a0575c474ea9bc5587d3554608a155307111c # main (2026-05-15)
        if: ${{ ! steps.releaseMode.outputs.dryRun }}
        with:
          body: |
            This release is also available on the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=SocketSecurity.vscode-socket-security) and [OpenVSX Registry](https://open-vsx.org/extension/SocketSecurity/vscode-socket-security).
          files: ${{ steps.publishToOpenVSX.outputs.vsix-path }}
          pre-release: ${{ steps.releaseMode.outputs.preRelease }}
