on:
  push:
    tags:
      - "release/[0-9]+.[0-9]+.[0-9]+"
      - "prerelease/[0-9]+.[0-9]+.[0-9]+"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          dryRun: ${{ secrets.DRY_RUN }}
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          preRelease:
            if: 
              then:
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          dryRun:: ${{ secrets.DRY_RUN }}
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          preRelease: false
          registryUrl: https://marketplace.visualstudio.com
      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: ${{ secrets.DRY_RUN != 'true' }}
        with:
          files: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
